name: Build Workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.0.0

      - name: Use Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Copy Build and Commit
        run: |
          git clone https://github.com/tomvothecoder/tomvo.me --branch gh-pages --single-branch gh-pages

          # Delete the existing content
          cd gh-pages
          rm -r *
          echo 'tomvo.me' > CNAME

          # Move `/build` content into the root of `gh-pages`.
          mv ../build/* .
          # Handle client side routing with 404.html redirect.
          # Source: https://github.com/rafgraph/spa-github-pages
          cp ../404.html .

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # The below command will fail if no changes were present, so we ignore it
          git add .
          git commit -m "Deploy build" -a || true

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
